version: "3"

services:
      
  nodered:
    container_name: teamprojekt_nodered
    build: ./nodeRed
    restart: unless-stopped
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - nodered:/data
    ports:
      - "1880:1880"
  
  mqtt:
    image: eclipse-mosquitto
    container_name: teamprojekt_mqtt
    restart: unless-stopped
    #network_mode: host
    volumes:
      - ./mqtt:/mosquitto/config
      - mqtt:/mosquitto/data
      - mqtt:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  mysql:
    container_name: teamprojekt_mysql
    build: ./database
    restart: unless-stopped
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - mysql:/var/lib/mysql
      
  adminer:
    image: adminer
    container_name: teamprojekt_mysql_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - "GF_PATHS_CONFIG=/etc/grafana/provisioning/config/grafana.ini"
      - "GF_INSTALL_PLUGINS=https://github.com/tkurki/grafana-track-map/archive/master.zip;plugins"
    volumes:
      - grafana:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
      
volumes:
  nodered:
  mqtt:
  mysql:
  grafana:
