version: "3"

services:
      
  nodered:
    container_name: "NodeRed"
    image: nodered/node-red
    restart: unless-stopped
    volumes:
      - nodered:/data
    ports:
      - "1880:1880"
  
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mqtt:/mosquitto/config
      - mqtt:/mosquitto/data
      - mqtt:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  mysql:
    container_name: teamprojekt_mysql
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=j6VfJuThHtTFgdYYZgUs
      - MYSQL_DATABASE=GPS
      - MYSQL_USER=grafana
      - MYSQL_PASSWORD=kRXb4cJBU8WTgDGvTXDp
    volumes:
      - mysql:/var/lib/mysql
      
  adminer:
    image: adminer
    container_name: teamprojekt_mysql_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
      
volumes:
  nodered:
  mqtt:
  mysql:
  grafana:
