apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    isDefault: true
    url: teamprojekt_mysql
    database: GPS
    user: grafana
    jsonData:
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: kRXb4cJBU8WTgDGvTXDp